### ISSUE TITLE
Password as plain text 

### ISSUE THREAD

**Issue by Maximus169** [akayohonda/Logining#2]
Password should be hashed (SHA)

**Для кого:**
Для студентов **АСОИ**, **ПО** и **ИИ**

**Что сделать:**
- Поставить себя в _Assignees_
- Пофиксить, создать pull-request с фиксом.
- Линкануть ПР к текущей issue.
- Попросить создателя проекта проверить и смержить Ваши изменения.

**Награда:**
Один плюсик

**Comment by akayohonda** [comment]
https://github.com/akayohonda/Logining
